import React from 'react';
import Root from '../components/common/Root';
import Footer from '../components/common/Footer';

const About = () => (
  <Root>
    <div className="about-container">
      {/* Row */}
      <div className="row mt-5 pt-5 about-hero">
            <div className="h-100 d-flex flex-column py-5 px-4 px-sm-5 justify-content-center">
              <h2 className="font-size-header mb-4">
  Data Privacy Policy
              </h2>
              <h4 className="font-size-subheader mb-4">
  <h4 className="font-size-subheader mb-4"> I. STORAGE OF ACCESS DATA IN SERVER LOGFILES. </h4>
  You may visit our website without providing any personal information. We store only access data in server logfiles, such as the name of the requested file, the date and time of the request, the quantity of data transmitted, and the requesting provider. This data is evaluated exclusively for the purpose of ensuring the fault-free functioning of the site and for improving the quality of our service and does not permit any conclusions to be drawn concerning your identity.

<h4 className="font-size-subheader mb-4"> II. DATA COLLECTION AND USE FOR PERFORMANCE OF A CONTRACT AND UPON OPENING OF A CUSTOMER ACCOUNT. </h4>

We collect, store, and process your data for handling your purchase and processing any subsequent warranty claims. Personal data is collected if you voluntarily provide it in the course of your order of goods, when opening a customer account, or when registering to receive the newsletter.
  The specific data collected may be seen from the corresponding input forms.
  When you register for the newsletter, your e-mail address is used for our own internal advertising purposes until you unsubscribe from the newsletter. You can unsubscribe at any time using the link provided in each newsletter.
  We share your personal data with the external service providers whose services are used in the fulfillment of your order (shippers, logistics companies, payment service providers, banks).
Once the contract has been fully performed or your customer acount deleted, your data will be blocked form further use and deleted as soon as applicable tax and commercial law permits, unless you have explicitly consented to the further use of your data or we have reserved the right to make further use of your data as permitted by law and of which we have informed you below. You may delete your customer account at any time, and may do so by using the corresponding function in your customer account.

<h4 className="font-size-subheader mb-4"> III. REGISTRATION FOR E-MAIL NEWSLETTER </h4>

If you have separately registered to receive the newsletter, your e-mail address will be used for our own advertising purposes. You will regularly be sent an e-mail newsletter until you unregister. You may revoke your registration at any time at no charge, except for any data transmission costs assessed by your Internet access provider on the basis of its standard rates for such services.

<h4 className="font-size-subheader mb-4"> IV. USE OF COOKIES </h4>

In order to make the use of our website more attractive and enable the use of particular functions, we use “cookies” on various pages of the site. These are small text files which are stored on your terminal device. Some of the cookies we used are deleted after the end of your browser session, i.e. once your browser is closed (session cookies). Other cookies remain on your terminal device, and enable us or our partner companies to recognize your browser on your next visit (persistent cookies).
You can change your browser settings to ensure that you are informed of the placing of any cookies, and may decide individually whether to accept a cookie in a particular case or exclude them in general. Failure to accept cookies may limit the functionality of our website.

<h4 className="font-size-subheader mb-4"> V. DATA SECURITY </h4>

Your payment information is transmitted through the Internet in encrypted form during the order process. We take technical and organization measures to protect our website and other systems against loss, destruction, access, modification, or disclosure of your data by unauthorized persons. You should always treat your access information as confidential and close the browser window once you have finished your communication with us, especially if you are using a shared computer.
  We store the text of the contract and send you the order data and our General Terms and Conditions via e-mail. You can also see our General Terms and Conditions at any time here.

<h4 className="font-size-subheader mb-4"> VI. USE OF GOOGLE ANALYTICS FOR WEB ANALYSIS </h4>


This website uses Google Analytics, a web analytics service provided by Google, Inc. (“Google”). Google Analytics uses “cookies”, which are text files placed on your computer, to help the website analyze how users use the site. The information generated by the cookie about your use of the website (including your IP address) will be transmitted to and stored by Google on servers in the United States. In case of activation of the IP anonymization, Google will truncate/anonymize the last octet of the IP address for Member States of the European Union as well as for other parties to the Agreement on the European Economic Area. Only in exceptional cases, the full IP address is sent to and shortened by Google servers in the USA. On behalf of the website provider Google will use this information for the purpose of evaluating your use of the website, compiling reports on website activity for website operators and providing other services relating to website activity and internet usage to the website provider. Google will not associate your IP address with any other data held by Google. You may refuse the use of cookies by selecting the appropriate settings on your browser. However, please note that if you do this, you may not be able to use the full functionality of this website. Furthermore you can prevent Google’s collection and use of data (cookies and IP address) by downloading and installing the browser plug-in available <a href="https://tools.google.com/dlpage/gaoptout?hl=en-GB" target="_blank" className="cjs-link" rel="noopener noreferrer">here</a>.
  Further information concerning the terms and conditions of use and data privacy can be found <a href="http://www.google.com/analytics/terms/gb.html" target="_blank" className="cjs-link" rel="noopener noreferrer">here</a>  or <a href="http://www.google.com/intl/en_uk/analytics/privacyoverview.html" target="_blank" className="cjs-link" rel="noopener noreferrer">here</a> .
  Please note that on this website, Google Analytics code is supplemented by “gat._anonymizeIp();” to ensure an anonymized collection of IP addresses (so called IP-masking).

<h4 className="font-size-subheader mb-4"> VII. RIGHT TO INFORMATION AND CONTACT METHODS </h4>


You have the right to be informed free of charge of your personal data stored by us, as well as, if applicable, a right to have such data corrected, blocked, or deleted. For questions relating to the collection, processing, or use of your personal data, for receiving information, correcting, blocking, or deleting such data, or for the revocation of consent previously granted or objections to a particular use of your data, please contact us directly by means of the contact information provided in our legal notice..
              </h4>
            </div>
      </div>
      {/* Row 4 */}

    </div>
    <Footer />
  </Root>
);

export default About;
